task-15
mativagon/testguru pull request #14
Opened 2022-10-15 14:13 UTC by mativagon

2022-10-15 17:21 UTC, BubuntuClu requested changes

2022-10-15 17:21 UTC, BubuntuClu commented on app/javascript/packs/registration.js
> +    if (confirmation.value == '') { return null }
`Не информируйте пользователя если поле подтверждения пароля не содержит значения`

если что-то ввести и потом очистить, то выделение компонентов не очистится.

`null` возвращать не обязательно, можно пустой ретурн сделать

2022-10-21 03:57 UTC, VidgarVii commented on app/assets/stylesheets/global.scss
> +}
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-10-21 03:57 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +    let control = document.getElementById('new_user')
если переменная не переопределяется, то принято считать её константой. Так безопасней

2022-10-23 15:08 UTC, merged